packages:
  - patchnotes-web
  - patchnotes-email
injectWorkspacePackages: true
catalog:
  "@typescript/native-preview": latest
  typescript: ~5.9.3
  react: ^19.2.4
  "@types/react": ^19.2.14
  "@types/node": 22.x
  tailwindcss: ^4.1.18
  vitest: ^4.0.18
onlyBuiltDependencies:
  - esbuild
  - msw
