/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticateRouteImport } from './routes/authenticate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReleasesReleaseIdRouteImport } from './routes/releases.$releaseId'
import { Route as PackagesPackageIdRouteImport } from './routes/packages.$packageId'

const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticateRoute = AuthenticateRouteImport.update({
  id: '/authenticate',
  path: '/authenticate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesReleaseIdRoute = ReleasesReleaseIdRouteImport.update({
  id: '/releases/$releaseId',
  path: '/releases/$releaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesPackageIdRoute = PackagesPackageIdRouteImport.update({
  id: '/packages/$packageId',
  path: '/packages/$packageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/authenticate': typeof AuthenticateRoute
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/packages/$packageId': typeof PackagesPackageIdRoute
  '/releases/$releaseId': typeof ReleasesReleaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/authenticate': typeof AuthenticateRoute
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/packages/$packageId': typeof PackagesPackageIdRoute
  '/releases/$releaseId': typeof ReleasesReleaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/authenticate': typeof AuthenticateRoute
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/packages/$packageId': typeof PackagesPackageIdRoute
  '/releases/$releaseId': typeof ReleasesReleaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/authenticate'
    | '/login'
    | '/preview'
    | '/packages/$packageId'
    | '/releases/$releaseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/authenticate'
    | '/login'
    | '/preview'
    | '/packages/$packageId'
    | '/releases/$releaseId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/authenticate'
    | '/login'
    | '/preview'
    | '/packages/$packageId'
    | '/releases/$releaseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthenticateRoute: typeof AuthenticateRoute
  LoginRoute: typeof LoginRoute
  PreviewRoute: typeof PreviewRoute
  PackagesPackageIdRoute: typeof PackagesPackageIdRoute
  ReleasesReleaseIdRoute: typeof ReleasesReleaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticate': {
      id: '/authenticate'
      path: '/authenticate'
      fullPath: '/authenticate'
      preLoaderRoute: typeof AuthenticateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/$releaseId': {
      id: '/releases/$releaseId'
      path: '/releases/$releaseId'
      fullPath: '/releases/$releaseId'
      preLoaderRoute: typeof ReleasesReleaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$packageId': {
      id: '/packages/$packageId'
      path: '/packages/$packageId'
      fullPath: '/packages/$packageId'
      preLoaderRoute: typeof PackagesPackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthenticateRoute: AuthenticateRoute,
  LoginRoute: LoginRoute,
  PreviewRoute: PreviewRoute,
  PackagesPackageIdRoute: PackagesPackageIdRoute,
  ReleasesReleaseIdRoute: ReleasesReleaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
